name = "yapyup"
main = "packages/server/src/index.ts"
compatibility_date = "2025-04-01"
route = "yapyup.com/*"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"

[assets]
directory = "packages/client/dist"
not_found_handling = "single-page-application"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "yapyup"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
