/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as AuthSignUpImport } from './routes/_auth/sign-up'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as AuthSetOrganisationImport } from './routes/_auth/set-organisation'
import { Route as AuthResetPasswordImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthCreateOrganisationImport } from './routes/_auth/create-organisation'
import { Route as AuthAcceptInvitationInvitationIdImport } from './routes/_auth/accept-invitation.$invitationId'
import { Route as ProtectedDashboardOrgOrgIdIndexImport } from './routes/_protected/dashboard/org/$orgId/index'
import { Route as ProtectedDashboardOrgOrgIdUserUserIdImport } from './routes/_protected/dashboard/org/$orgId/user/$userId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_protected/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthSetOrganisationRoute = AuthSetOrganisationImport.update({
  id: '/_auth/set-organisation',
  path: '/set-organisation',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthCreateOrganisationRoute = AuthCreateOrganisationImport.update({
  id: '/_auth/create-organisation',
  path: '/create-organisation',
  getParentRoute: () => rootRoute,
} as any)

const AuthAcceptInvitationInvitationIdRoute =
  AuthAcceptInvitationInvitationIdImport.update({
    id: '/_auth/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRoute,
  } as any)

const ProtectedDashboardOrgOrgIdIndexRoute =
  ProtectedDashboardOrgOrgIdIndexImport.update({
    id: '/org/$orgId/',
    path: '/org/$orgId/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardOrgOrgIdUserUserIdRoute =
  ProtectedDashboardOrgOrgIdUserUserIdImport.update({
    id: '/org/$orgId/user/$userId',
    path: '/org/$orgId/user/$userId',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/create-organisation': {
      id: '/_auth/create-organisation'
      path: '/create-organisation'
      fullPath: '/create-organisation'
      preLoaderRoute: typeof AuthCreateOrganisationImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_auth/set-organisation': {
      id: '/_auth/set-organisation'
      path: '/set-organisation'
      fullPath: '/set-organisation'
      preLoaderRoute: typeof AuthSetOrganisationImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_auth/accept-invitation/$invitationId': {
      id: '/_auth/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AuthAcceptInvitationInvitationIdImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard/org/$orgId/': {
      id: '/_protected/dashboard/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/dashboard/org/$orgId'
      preLoaderRoute: typeof ProtectedDashboardOrgOrgIdIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/dashboard/org/$orgId/user/$userId': {
      id: '/_protected/dashboard/org/$orgId/user/$userId'
      path: '/org/$orgId/user/$userId'
      fullPath: '/dashboard/org/$orgId/user/$userId'
      preLoaderRoute: typeof ProtectedDashboardOrgOrgIdUserUserIdImport
      parentRoute: typeof ProtectedDashboardImport
    }
  }
}

// Create and export the route tree

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardOrgOrgIdIndexRoute: typeof ProtectedDashboardOrgOrgIdIndexRoute
  ProtectedDashboardOrgOrgIdUserUserIdRoute: typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardOrgOrgIdIndexRoute: ProtectedDashboardOrgOrgIdIndexRoute,
  ProtectedDashboardOrgOrgIdUserUserIdRoute:
    ProtectedDashboardOrgOrgIdUserUserIdRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-organisation': typeof AuthCreateOrganisationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-organisation': typeof AuthSetOrganisationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/org/$orgId': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create-organisation': typeof AuthCreateOrganisationRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-organisation': typeof AuthSetOrganisationRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/dashboard/org/$orgId': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_auth/create-organisation': typeof AuthCreateOrganisationRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-organisation': typeof AuthSetOrganisationRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_auth/accept-invitation/$invitationId': typeof AuthAcceptInvitationInvitationIdRoute
  '/_protected/dashboard/org/$orgId/': typeof ProtectedDashboardOrgOrgIdIndexRoute
  '/_protected/dashboard/org/$orgId/user/$userId': typeof ProtectedDashboardOrgOrgIdUserUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create-organisation'
    | '/forgot-password'
    | '/reset-password'
    | '/set-organisation'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/accept-invitation/$invitationId'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create-organisation'
    | '/forgot-password'
    | '/reset-password'
    | '/set-organisation'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/accept-invitation/$invitationId'
    | '/dashboard/org/$orgId'
    | '/dashboard/org/$orgId/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_auth/create-organisation'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/set-organisation'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/dashboard'
    | '/_auth/accept-invitation/$invitationId'
    | '/_protected/dashboard/org/$orgId/'
    | '/_protected/dashboard/org/$orgId/user/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthCreateOrganisationRoute: typeof AuthCreateOrganisationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetOrganisationRoute: typeof AuthSetOrganisationRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  AuthAcceptInvitationInvitationIdRoute: typeof AuthAcceptInvitationInvitationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthCreateOrganisationRoute: AuthCreateOrganisationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetOrganisationRoute: AuthSetOrganisationRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  AuthAcceptInvitationInvitationIdRoute: AuthAcceptInvitationInvitationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/_auth/create-organisation",
        "/_auth/forgot-password",
        "/_auth/reset-password",
        "/_auth/set-organisation",
        "/_auth/sign-in",
        "/_auth/sign-up",
        "/_protected/dashboard",
        "/_auth/accept-invitation/$invitationId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_auth/create-organisation": {
      "filePath": "_auth/create-organisation.tsx"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx"
    },
    "/_auth/reset-password": {
      "filePath": "_auth/reset-password.tsx"
    },
    "/_auth/set-organisation": {
      "filePath": "_auth/set-organisation.tsx"
    },
    "/_auth/sign-in": {
      "filePath": "_auth/sign-in.tsx"
    },
    "/_auth/sign-up": {
      "filePath": "_auth/sign-up.tsx"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "children": [
        "/_protected/dashboard/org/$orgId/",
        "/_protected/dashboard/org/$orgId/user/$userId"
      ]
    },
    "/_auth/accept-invitation/$invitationId": {
      "filePath": "_auth/accept-invitation.$invitationId.tsx"
    },
    "/_protected/dashboard/org/$orgId/": {
      "filePath": "_protected/dashboard/org/$orgId/index.tsx",
      "parent": "/_protected/dashboard"
    },
    "/_protected/dashboard/org/$orgId/user/$userId": {
      "filePath": "_protected/dashboard/org/$orgId/user/$userId.tsx",
      "parent": "/_protected/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
